Whack/config/routes.rb
  Rails.application.routes.draw do
  root    'users#new'

  resources :comments
  resources :users
  resources :answers, only: [:new, :update, :destroy]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :questions do
    resources :votes, only: [:new, :create]
    resources :comments, except: [:edit]
    resources :answers, only: [:new, :create, :edit] do
      resources :comments, except: [:edit]
      resources :votes, only: [:new, :create]
    end
  end

end

Whack/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
	has_many :comments, as: :commentable
	has_many :votes, as: :votable
  validates :body, presence: true

  def vote_count
    self.votes.pluck(:votevalue).sum
  end

end

Whack/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :get_answer, only: [:edit, :update, :destroy ]

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def edit

  end

  # ---> needs routes
  # and view that renders form --> sending in the right variables
  # (either somehow keeping @s or creating local varibales with locals: method )

  def create
    @answer = Answer.new(answer_params)
    # .update is usually called on a save db object... I'd rather you create the object with the proper
    # params to begin with.  Maybe:
    # @anwser = current_user.anwswers.build(answer_params.merge(
    #   question_id: params[:question_id]
    # ))
    #
    @answer.update(user_id: session[:user_id], question_id: params[:question_id])
    if @answer.save
      redirect_to question_path(@answer.question)
    else
      flash[:warn] = "Sorry that answer was not created. Please try again."
      redirect_to :back
    end
  end

  def update
    # I think you want
    # if @answer.update(answer_params)
    #   redirect....
    #
    # update will update the object and return true if saved or false if unable
    @answer.update(answer_params)
    if @answer.save
       redirect_to question_path(@question)
    else
      flash[:warn] = "Sorry that answer was not created. Please try again."
      redirect_to :back
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def destroy
    @answer.destroy
    redirect_to answer_path(@answer)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def get_answer
    @answer = Answer.find(params[:id])
  end
end

Whack/app/helpers/answer_helper.rb
module AnswerHelper
end

Whack/app/views/answers/_answer.html.erb
<div class='answer_partial'>
  <%= render partial: 'votes/ansnew', locals: {question: answer.question, answer: answer} %>
  <p><%= answer.body %></p>

    <ol>
      <% answer.comments.each do |c| %>
        <li><%= render partial: 'comments/comment', locals: {comment: c} %></li>
      <% end %>
    </ol>
  <div class="links">
    <%= link_to 'new comment', new_question_answer_comment_path(answer.question, answer)  %>
    <% if session[:user_id] == answer.user_id %>
      <%= link_to 'edit', edit_question_answer_path(answer.question, answer)  %>
      <%= link_to 'delete', answer, method: :delete, data: { confirm: 'sure?'} %>
    <% end %>
  </div>
</div>

Whack/app/views/answers/_form.html.erb
<div>
  <%= form_for ([@question, @answer]) do |f| %>
   <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@answer.errors.count, "error") %> stopped this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
   </div>
  <% end %>
    <p>
      <%= f.label :answer %><br>
      <%= f.text_field :body %>
    </p>
    <p>
      <%= f.submit 'New answer'    %>
    </p>
  <% end %>
</div>

Whack/app/views/answers/edit.html.erb
<h1>Edit Answer</h1>
<%= render 'form' %>

Whack/app/views/answers/new.html.erb
<div>New Answer</div>
<%= render partial: 'form' %>