Whack/config/routes.rb
  Rails.application.routes.draw do
  root    'users#new'

  resources :comments
  resources :users
  resources :answers, only: [:new, :update, :destroy]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :questions do
    resources :votes, only: [:new, :create]
    resources :comments, except: [:edit]
    resources :answers, only: [:new, :create, :edit] do
      resources :comments, except: [:edit]
      resources :votes, only: [:new, :create]
    end
  end

end

Whack/app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
	has_many :comments, as: :commentable # Good use of Polymorphic associations
	has_many :votes, as: :votable
  validates :body, presence: true
  validates :title, presence: true

  def vote_count
    self.votes.pluck(:votevalue).sum
  end

  def self.most_popular
    # Move the sort into the database.  Also, usually you want to limit the number of records returned
    Question.all.sort_by {|q| q.vote_count}.reverse
  end

  def sorted_answers
    # Again - do the sort database side
    self.answers.sort_by {|question| question.vote_count}.reverse
  end

end

Whack/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


	def index
		@questions = Question.includes(:comments).most_popular # Good
	end

	def show
		@question = Question.includes(:comments, :answers).find(params[:id])
	end

	def new
		@question = Question.new
	end

	def create
		# h = question_params
		# h[:user_id] = session[:user_id]
		#@question = Question.new(h)
		@question = current_user.questions.build(question_params) # This is more idiomatic
		if @question.save
			redirect_to @question
		else
			render :new
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		h = question_params
		h[:user_id] = session[:user_id]
		if @question.update_attributes(h) # Dont use update_attributes.  It bypasses validations.  Use .update
			redirect_to @question
		else
			render :edit
		end
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		redirect_to root_url
	end



	private
		def question_params
			params.require(:question).permit(:title, :body)
		end

end

Whack/app/helpers/questions_helper.rb
module QuestionsHelper
end

Whack/app/views/questions/_form.html.erb
<div class="question-form">
	<%= form_for(@question) do |f| %>
		<div class="field q-title">
	    <%= f.label :title %><br>
	    <%= f.text_field :title %>
	  </div>
  	<div class="field q-body">
      <%= f.label :body %><br>
      <%= f.text_field :body %>
    </div>
		<div class="action q-submit">
			<%= f.submit %>
		</div>

	<% end %>
</div>

Whack/app/views/questions/_index.html.erb
<div class="list-users-links">
	<% if @questions %>
		<% @questions.each do |question| %>
			<div><%= link_to question.title, question_path(question)  %></div>
		<% end %>
	<% end %>
</div>

Whack/app/views/questions/_question.html.erb
<div class="question-partial">

  <%= render partial: 'votes/questnew', locals: {question: @question} %>
  <h2 class='question_title'><%= question.title %></h2>
  <br>
  <br>
  <h5><%= question.body %></h5>

  <% comments.each do |c| %>
    <%= render partial: 'comments/comment', locals: {comment: c} %>
  <% end %>
  <div class="links">
  	<%= link_to 'new comment', new_question_comment_path(question)  %>
  	<% if session[:user_id] == question.user_id %>
      <%= link_to 'edit', edit_question_path(question)  %>
      <%= link_to 'delete', question, method: :delete, data: { confirm: 'sure?'} %>
    <% end %>
  </div>
</div>

Whack/app/views/questions/edit.html.erb
<h1>questions edit</h1>

<%= render 'form' %>

Whack/app/views/questions/index.html.erb
<div class="list-users">
  <% if @questions %>
    <% @questions.each do |question| %>
      <p class='q-list'><%= link_to question.title, question_path(question)  %></p>
    <% end %>
  <% end %>
</div>

Whack/app/views/questions/new.html.erb
<%= render partial: 'form', locals: {question: @question} %>

Whack/app/views/questions/show.html.erb
<div class='block'>
  <div class='question_partial'>
    <%= render partial: 'question', locals: {question: @question,
    																				comments: @question.comments}  %>
  <div><h1>Answers: </h1></div>
    <ol>
      <% @question.sorted_answers.each do |a| %>
        <li><%= render partial: 'answers/answer', locals: {answer: a} %></li>
      <% end %>
    </ol>
  </div>
  <% @answer = Answer.new %>
  <%= render partial: 'answers/form', locals: {answer: @answer, question: @question}  %>
</div>