Whack/config/routes.rb
  Rails.application.routes.draw do
  root    'users#new'

  resources :comments
  resources :users
  resources :answers, only: [:new, :update, :destroy]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :questions do
    resources :votes, only: [:new, :create]
    resources :comments, except: [:edit]
    resources :answers, only: [:new, :create, :edit] do
      resources :comments, except: [:edit]
      resources :votes, only: [:new, :create]
    end
  end

end

Whack/app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :votable, polymorphic: true

  validates :user_id, presence: true
  validates :votevalue, presence: true
  validates :votable_id, presence: true
  validates :votable_type, presence: true
end

Whack/app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:answer_id])
    @vote = Vote.new
  end

  def create
    # This needs a refactor - I leave it to you to determine how
    if params[:answer_id]
      @answer = Answer.find(params[:answer_id])
      vote = Vote.new(user_id: session[:user_id], votable_id: params[:answer_id])
      vote[:votable_type] = 'Answer'
      vote.update(votevalue: params[:vote])
      vote.save
      @answer.votes << vote
      redirect_to @answer.question
    elsif params[:question_id]
      @question = Question.find(params[:question_id])
      vote = Vote.new(user_id: session[:user_id], votable_id: params[:question_id])
      vote[:votable_type] = 'Question'
      vote.update(votevalue: params[:vote])
      vote.save
      @question.votes << vote
      redirect_to @question
    end
  end

  private

  def votetype
    params.require(:vote).permit(:votevalue)
  end

end

Whack/app/views/votes/_ansnew.html.erb
<div class='upvote'>
  <%= link_to question_answer_votes_path(answer.question, answer, vote: 1), method: 'post' do %>
    <i class='question_up_vote'><%= image_tag 'tiny_arrow_up.gif' %></i>
  <% end %>
</div>
<div class='count'><%= answer.vote_count %></div>
<div class='downvote'>
  <%= link_to question_answer_votes_path(answer.question, answer, vote: -1), method: 'post' do %>
    <i class='question_up_vote'><%= image_tag 'tiny_arrow_down.gif' %></i>
  <% end %>
</div>

Whack/app/views/votes/_questnew.html.erb
<div class='upvote'>
  <%= link_to question_votes_path(@question, vote: 1), method: 'post' do %>
    <i class='question_up_vote'><%= image_tag 'tiny_arrow_up.gif' %></i>
  <% end %>
</div>
<div class='count'><%= @question.vote_count %></div>
<div class='downvote'>
  <%= link_to question_votes_path(@question, vote: -1), method: 'post' do %>
    <i class='question_up_vote'><%= image_tag 'tiny_arrow_down.gif' %></i>
  <% end %>
</div>