Whack/config/routes.rb
  Rails.application.routes.draw do
  root    'users#new'

  resources :comments
  resources :users
  resources :answers, only: [:new, :update, :destroy]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :questions do
    resources :votes, only: [:new, :create]
    resources :comments, except: [:edit]
    resources :answers, only: [:new, :create, :edit] do
      resources :comments, except: [:edit]
      resources :votes, only: [:new, :create]
    end
  end

end

Whack/app/views/layouts/_header.html.erb
<h1>Whack Overflow</h1>
<div id='cssmenu'>
<ul>
  <% if session[:user_id] %>
   <li><%= link_to 'Home', questions_path  %></li>
   <li><%= link_to 'Create a new Question', new_question_path %></a></li>
   <li><%= link_to "Logout", logout_path, method: 'delete' %></li>
  <% else %>
   <li class='active'><%= link_to 'Home', new_user_path  %></li>
   <li><%= link_to "Login", login_path %></li>
   <li class='last'><%= link_to "Sign Up", new_user_path %></li>
  <% end %>
</ul>
</div>

Whack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<div class="inner-header">
			<%= render 'layouts/header' %>
		</div>
	</header>

	<div class="main">
		<div class="inner-main">
			<%= yield %>
		</div>
	</div>

	<footer>
		<div class="inner-footer">

		</div>
	</footer>

</body>
</html>